### ISSUE TITLE
write to hbase table exception

### ISSUE THREAD

**Issue by henryon** [nerdammer/spark-hbase-connector#19]
I am using hdp 2.2 and recompile spark-1.5.2 with jackson package.
but when I run "rdd.toHBaseTable("mytable").toColumns("column1", "column2").inColumnFamily("mycf").save()"

it failed, seems to connect to localhost zk server, how to fix it. I have to specify it in code or configure some files make it work(connect to right server)

thanks.
#########log info #################
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2016-02-24 12:48:44,286 INFO  [Executor task launch worker-2-SendThread(localhost:2181)] zookeeper.ClientCnxn: Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
2016-02-24 12:48:44,286 WARN  [Executor task launch worker-2-SendThread(localhost:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2016-02-24 12:48:44,291 WARN  [Executor task launch worker-2] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/hbaseid
2016-02-24 12:48:45,387 INFO  [Executor task launch worker-2-SendThread(localhost:2181)] zookeeper.ClientCnxn: Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2016-02-24 12:48:45,387 WARN  [Executor task launch worker-2-SendThread(localhost:2181)] zookeeper.ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)

**Comment by nibbio84** [comment]
Hi, you might need to set the "spark.hbase.host" property in order to connect to a machine other than localhost. 
You can use the JVM option -Dspark.hbase.host=the host for this purpose.
I'll update the docs, as it is not clear.

**Comment by henryon** [comment]
@nibbio84  thanks for your update. 
Assume I take spark.hbase.host as hbase master? right. If so, I 
also I use spark-shell, just want to confirm how to pass it. like below?
 ./spark-shell --jars jarfile --driver-java-options   spark.hbase.host=hmasterFQDN
I tried it. Doesn't work. 
Thanks a lot.

**Comment by nibbio84** [comment]
Not the hbase master, you need to pass the zookeeper quorum host (that listens on port 2181).

**Comment by nibbio84** [comment]
Also, use the --conf option if you launch it from the shell.

**Comment by henryon** [comment]
thanks @nibbio84 

it's worked. but failed to create table 

######logs#####################
016-02-25 16:37:20,642 INFO  [Executor task launch worker-3] mapreduce.TableOutputFormat: Created table instance for mytable
2016-02-25 16:37:20,642 INFO  [Executor task launch worker-1] mapreduce.TableOutputFormat: Created table instance for mytable
2016-02-25 16:37:20,642 INFO  [Executor task launch worker-2] mapreduce.TableOutputFormat: Created table instance for mytable
2016-02-25 16:37:20,642 INFO  [Executor task launch worker-0] mapreduce.TableOutputFormat: Created table instance for mytable
2016-02-25 16:37:20,678 DEBUG [Executor task launch worker-0] hbase.HRegionInfo: 1588230740
2016-02-25 16:37:20,828 DEBUG [Executor task launch worker-0] ipc.RpcClient: Use SIMPLE authentication for service ClientService, sasl=false
2016-02-25 16:37:20,839 DEBUG [Executor task launch worker-0] ipc.RpcClient: Connecting to dn02.uat.ev.com/10.50.1.227:60020
2016-02-25 16:37:20,849 WARN  [Executor task launch worker-0] client.ConnectionManager$HConnectionImplementation: Encountered problems when prefetch hbase:meta table:
org.apache.hadoop.hbase.TableNotFoundException: Cannot find row in hbase:meta for table: mytable, row=mytable,1,99999999999999
	at org.apache.hadoop.hbase.client.MetaScanner.metaScan(MetaScanner.java:164)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.prefetchRegionCache(ConnectionManager.java:1222)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegionInMeta(ConnectionManager.java:1286)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1135)
	at org.apache.hadoop.hbase.client.AsyncProcess.submit(AsyncProcess.java:362)
	at org.apache.hadoop.hbase.client.AsyncProcess.submit(AsyncProcess.java:313)
	at org.apache.hadoop.hbase.client.HTable.backgroundFlushCommits(HTable.java:1066)
	at org.apache.hadoop.hbase.client.HTable.flushCommits(HTable.java:1344)
	at org.apache.hadoop.hbase.client.HTable.close(HTable.java:1380)
	at org.apache.hadoop.hbase.mapreduce.TableOutputFormat$TableRecordWriter.close(TableOutputFormat.java:112)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$5.apply$mcV$sp(PairRDDFunctions.scala:1043)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1215)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1042)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1014)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2016-02-25 16:37:20,852 ERROR [Executor task launch worker-0] client.AsyncProcess: Failed to get region location
org.apache.hadoop.hbase.TableNotFoundException: mytable
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegionInMeta(ConnectionManager.java:1319)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1135)
	at org.apache.hadoop.hbase.client.AsyncProcess.submit(AsyncProcess.java:362)
	at org.apache.hadoop.hbase.client.AsyncProcess.submit(AsyncProcess.java:313)
	at org.apache.hadoop.hbase.client.HTable.backgroundFlushCommits(HTable.java:1066)
	at org.apache.hadoop.hbase.client.HTable.flushCommits(HTable.java:1344)
	at org.apache.hadoop.hbase.client.HTable.close(HTable.java:1380)
	at org.apache.hadoop.hbase.mapreduce.TableOutputFormat$TableRecordWriter.close(TableOutputFormat.java:112)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$5.apply$mcV$sp(PairRDDFunctions.scala:1043)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1215)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1042)

**Comment by nibbio84** [comment]
That's because the table should be created manually before writing to it. There are many options that you can declare when creating a table, that's why the library doesn't take care of the table creation phase.

**Comment by henryon** [comment]
I see. thanks @nibbio84

**Comment by henryon** [comment]
@nibbio84  it seems this jar not support filter function as hbase. I found the withstartrowwithstoprow like hbase scan function. 

is there anyway can support hbase filter function? like  scan 't1', {FILTER => "(PrefixFilter ('row2') AND
    (QualifierFilter (>=, 'binary:xyz'))) AND (TimestampsFilter ( 123, 456))"}

many thanks.

**Comment by nicolaferraro** [comment]
No, the connector just supports just the scan range for filtering rows.

**Comment by surrey-kapkoti** [comment]
Hi
I have created the table but it is still not able to write to the table and logs the following:

16/08/19 06:38:11 INFO RpcRetryingCaller: Call exception, tries=10, retries=35, started=38439 ms ago, cancelled=false, msg=row 'TableForSpark,1,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=ip-10-60-0-xxx.ec2.internal,16020,1471529327629, seqNum=0
16/08/19 06:38:11 INFO RpcRetryingCaller: Call exception, tries=10, retries=35, started=38497 ms ago, cancelled=false, msg=row 'TableForSpark,7,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=ip-10-60-0-xxx.ec2.internal,16020,1471529327629, seqNum=0
16/08/19 06:38:11 INFO RpcRetryingCaller: Call exception, tries=10, retries=35, started=38499 ms ago, cancelled=false, msg=row 'TableForSpark,3,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=ip-10-60-0-xxx.ec2.internal,16020,1471529327629, seqNum=0
16/08/19 06:38:11 INFO RpcRetryingCaller: Call exception, tries=10, retries=35, started=38535 ms ago, cancelled=false, msg=row 'TableForSpark,5,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=ip-10-60-0-xxx.ec2.internal,16020,1471529327629, seqNum=0
16/08/19 06:38:11 INFO RpcRetryingCaller: Call exception, tries=10, retries=35, started=38557 ms ago, cancelled=false, msg=row 'TableForSpark,9,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=ip-10-60-0-xxx.ec2.internal,16020,1471529327629, seqNum=0

**Comment by gtarcoder** [comment]
@surrey-kapkoti 
Hi, did you solved that problem you posted? I have also met with that problem, and am struggling with it.

**Comment by TopSlugger** [comment]
@gtarcoder, I don't remember if i was able to fix it , it was quite long back :-) . If you want I can try it when I get some time.

**Comment by gtarcoder** [comment]
@TopSlugger  Thanks for your response, it would be great if you take a look at it if you have time.
