### ISSUE TITLE
spark streaming with hbase ERROR

### ISSUE THREAD

**Issue by slim-azaiz** [nerdammer/spark-hbase-connector#60]
i got this error :
17/10/30 09:20:51 ERROR Utils: Aborting task
java.lang.IllegalArgumentException: Wrong number of columns. Expected 4 found 3
        at it.nerdammer.spark.hbase.HBaseWriter$$anonfun$1.apply(HBaseWriterBuilder.scala:80)
        at it.nerdammer.spark.hbase.HBaseWriter$$anonfun$1.apply(HBaseWriterBuilder.scala:66)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at org.apache.spark.internal.io.SparkHadoopMapReduceWriter$$anonfun$4.apply(SparkHadoopMapReduceWriter.scala:147)
        at org.apache.spark.internal.io.SparkHadoopMapReduceWriter$$anonfun$4.apply(SparkHadoopMapReduceWriter.scala:144)
        at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1375)
        at org.apache.spark.internal.io.SparkHadoopMapReduceWriter$.org$apache$spark$internal$io$SparkHadoopMapReduceWriter$$executeTask(SparkHadoopMapReduceWriter.scala:159)
        at org.apache.spark.internal.io.SparkHadoopMapReduceWriter$$anonfun$3.apply(SparkHadoopMapReduceWriter.scala:89)
        at org.apache.spark.internal.io.SparkHadoopMapReduceWriter$$anonfun$3.apply(SparkHadoopMapReduceWriter.scala:88)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:108)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by nicolaferraro** [comment]
Can you share the code you used?

**Comment by slim-azaiz** [comment]
Thanks, i already fixed it (the problem was the number of columns)
