### ISSUE TITLE
Caused by: java.lang.RuntimeException: java.lang.NullPointerException 	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:208)

### ISSUE THREAD

**Issue by gypsysunny** [nerdammer/spark-hbase-connector#68]
I run across the issue described below:
Caused by: java.lang.NullPointerException
	at org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher.getMetaReplicaNodes(ZooKeeperWatcher.java:395)
	at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:553)
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getMetaRegionLocation(ZooKeeperRegistry.java:61)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateMeta(ConnectionManager.java:1186)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1153)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerWithReadReplicas.getRegionLocations(RpcRetryingCallerWithReadReplicas.java:300)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:155)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:59)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:200)

this is my code snippet:
 object positionSchema {
      val key = StructField("key", StringType, false)
      val xx = StructField("xx", StringType, true)
      val yy = StructField("yy", StringType, true)
      val struct = new StructType(Array(key, xx, yy))
    }

    // Create DataFrame with rowRDD and Schema structure
    import it.nerdammer.spark.hbase._
    val hBaseRDD = sc.hbaseTable[(Option[String], Option[String], Option[String])](tablename)
      .select("e", "i")
      .inColumnFamily("B")

      // Iterate HBaseRDD and generate RDD[Row]
    val rowRDD = hBaseRDD.map(i => Row(i._1.get,i._2.get,i._3.get))

    val positionDF = sparkSession.createDataFrame(rowRDD, positionSchema.struct)
    println("positionDF_count=" + positionDF.count())

Can anyone give any tips? thank you in advance.

**Comment by gypsysunny** [comment]
I found it is probably because that the baseZNode is not set to be "hbase-unsecure" although i have given sparkConf.set(HConstants.ZOOKEEPER_ZNODE_PARENT, "/hbase-unsecure"). it still shows "baseZNode=/hbase". so how do correctly set the very value?
